### ISSUE TITLE
TypeError: tensor or list of tensors expected, got <class 'numpy.ndarray'> 

### ISSUE THREAD

**Issue by brasanko** [hukkelas/DeepPrivacy#12]
Hi,
it seems like
Reading of the images is successfully completed, dataset is loaded, validation of the model seems to be completed too, but then the following error happens:

```
Traceback (most recent call last):
File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec)
File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals)
File "/workspace/deep_privacy/train.py", line 484, in <module> trainer.train()
File "/workspace/deep_privacy/train.py", line 464, in train self.maybe_validate_model()
File "/workspace/deep_privacy/train.py", line 412, in maybe_validate_model self.validate_model()
File "/workspace/deep_privacy/train.py", line 326, in validate_model log_to_validation=True)
File "/workspace/deep_privacy/logger.py", line 58, in save_images torchvision.utils.save_image(images, filepath, nrow=10)
File "/opt/conda/lib/python3.6/site-packages/torchvision/utils.py", line 101, in save_image normalize=normalize, range=range, scale_each=scale_each)
File "/opt/conda/lib/python3.6/site-packages/torchvision/utils.py", line 31, in make_grid raise TypeError('tensor or list of tensors expected, got {}'.format(type(tensor)))
TypeError: tensor or list of tensors expected, got <class 'numpy.ndarray'> 
```

I wrote a print statement to logger.py file to see which "images" are being forwarded to torchvision.utils.save_image function and I saw that the docker crashes every time fakes*.jpg images are forwarded into the save_image function. Their are of <class 'numpy.ndarray'> class, whereas all the others (at which the docker doesn't crash) are of torch.Tensor type. However, I wrote an if statement if the images are numpy array class, and I change their type when that happens into torch.Tensor, but then this error happens:

RuntimeError: The expanded size of the tensor (3) must match the existing size (8) at non-singleton dimension 0.  Target sizes: [3, 8, 3].  Tensor sizes: [8, 8, 3]

What can I do that it will go through as it should?

**Comment by hukkelas** [comment]
Hmm, this is a weird error. It might be something with torchvision versions. 

Anyways, to make the behaviour similar for each call to `save_images`, I changed the datatype to be a torch tensor.

Check out [this](https://github.com/hukkelas/DeepPrivacy/commit/12c1f5de3de1c25be778e8c344d7955a3cc5863e) commit for more info.

Hope this fixes your issue! Closing this for now.
