### ISSUE TITLE
Problem with command line 

### ISSUE THREAD

**Issue by daquarti** [hukkelas/DeepPrivacy#42]
Could you help me?
python3 anonymize.py -s/home/daqua/Pictures/h.png -t/home/daqua/Pictures/h2.png

None
Traceback (most recent call last):
File "anonymize.py", line 5, in
cli.main()
File "/home/daqua/Videos/DeepPrivacy/deep_privacy/cli.py", line 111, in main
anonymizer, cfg = build_anonymizer(
File "/home/daqua/Videos/DeepPrivacy/deep_privacy/build.py", line 62, in build_anonymizer
cfg = get_config(config_urls[model_name])
File "/home/daqua/Videos/DeepPrivacy/deep_privacy/build.py", line 36, in get_config
torch.hub.download_url_to_file(config_url, cfg_path)
File "/home/daqua/.local/lib/python3.8/site-packages/torch/hub.py", line 394, in download_url_to_file
u = urlopen(req)
File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.8/urllib/request.py", line 531, in open
response = meth(req, response)
File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
response = self.parent.error(
File "/usr/lib/python3.8/urllib/request.py", line 569, in error
return self._call_chain(*args)
File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
result = func(*args)
File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 308: Permanent Redirect

**Comment by andmagdo** [comment]
@daquarti
I have made a pull request [here](https://github.com/hukkelas/DeepPrivacy/pull/43/files).
However if you would like to use now, I have forked and fixed this issue and others [here](https://github.com/andmagdo/DeepPrivacy)

**Comment by hukkelas** [comment]
This is now merged.
