### ISSUE TITLE
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead. why？

### ISSUE THREAD

**Issue by zhq0918** [hukkelas/DeepPrivacy#7]
```
python3.6 -m deep_privacy.inference.anonymize_folder model/default/config.yml --source_path lina2.jpg --target_path lina2_anonymized.jpg
```
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/DeepPrivacy/deep_privacy/inference/anonymize_folder.py", line 1, in <module>
    from deep_privacy.inference import deep_privacy_anonymizer, infer
  File "/opt/DeepPrivacy/deep_privacy/inference/deep_privacy_anonymizer.py", line 7, in <module>
    from .anonymizer import Anonymizer
  File "/opt/DeepPrivacy/deep_privacy/inference/anonymizer.py", line 7, in <module>
    from deep_privacy.inference import infer
  File "/opt/DeepPrivacy/deep_privacy/inference/infer.py", line 5, in <module>
    from deep_privacy import config_parser, utils
  File "/opt/DeepPrivacy/deep_privacy/utils.py", line 4, in <module>
    from apex.amp._amp_state import _amp_state
  File "/usr/local/lib/python3.6/site-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/usr/local/lib/python3.6/site-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/usr/local/lib/python3.6/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/usr/local/lib/python3.6/site-packages/zope/interface/declarations.py", line 483, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
**TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.**
```
why？

**Comment by hukkelas** [comment]
This looks like a apex issue. Could you try installing the newest version of apex?

A similar issue was described [here](https://github.com/NVIDIA/apex/issues/116)

**Comment by zhq0918** [comment]
ok，thank you @hukkelas
